# Generated by Django 5.0.1 on 2024-06-12 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Alibaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Price_discount', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=255)),
                ('AttributeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.attribute')),
                ('CategoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attribute', to='web.category')),
            ],
        ),
        migrations.CreateModel(
            name='login_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name_Admin', models.CharField(max_length=100)),
                ('Last_name_Admin', models.CharField(max_length=100)),
                ('Phone_number_Admin', models.CharField(max_length=11)),
                ('Email_user_Admin', models.EmailField(max_length=100)),
                ('Passwoord_user_Admin', models.CharField(max_length=50)),
                ('Register_date_Admin', models.DateTimeField(verbose_name='date published')),
                ('ID_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('Passwoord', models.CharField(max_length=50)),
                ('Register_date', models.DateTimeField(verbose_name='date published')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOtalPraice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('TripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SateNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('Passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.passenger')),
                ('TripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=255)),
                ('AttributeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.attribute')),
                ('TripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.trip')),
            ],
        ),
    ]
