# Generated by Django 5.0.6 on 2024-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_categoryattribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
