# Generated by Django 5.0.6 on 2024-06-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_passenger_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiket',
            old_name='SateNumber',
            new_name='SeatNumber',
        ),
    ]
